workspace(name = "workspace")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

local_repository(
    name = "rules_deb_packages",
    path = "../../deb_packages",
)

load("@rules_deb_packages//:repositories.bzl", "deb_packages_dependencies")

deb_packages_dependencies()

http_file(
    name = "ubuntu_jammy_key",
    sha256 = "4e60bb785de3ce38902b451952f2ad2509048babff57290274e4e75c7476f94b",
    urls = ["https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf6ecb3762474eda9d21b7022871920d1991bc93c"],
)

load(":ubuntu_jammy_amd64.bzl", "ubuntu_jammy_amd64")

ubuntu_jammy_amd64()

load(":ubuntu_jammy_arm64.bzl", "ubuntu_jammy_arm64")

ubuntu_jammy_arm64()
