linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goimports:
    local-prefixes: github.com/ayoisaiah/f2
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
    ignored-functions:
      - strings.SplitN

  govet:
    check-shadowing: true
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true
    require-specific: true
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - godot
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

issues:
  fix: false
  exclude-rules:
    - path: _test\.go # disable some linters for test files
      linters:
        - gocyclo
        - gosec
        - dupl
    - linters:
        - gosec
      text: "weak cryptographic primitive"
    - linters:
        - stylecheck
      text: "error strings should not be capitalized"

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  issues-exit-code: 1
  skip-dirs:
    - test
    - tests
